AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >

  nodejs-sam-bootstrap
  SAM Template for nodejs-sam-bootstrap

#####  Globals for Lambda functions #####
Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        Region: "eu-west-1"

#####  Input Parameters #####
Parameters:
  Stage:
    Type: String
    Description: Parameter for getting the deployment stage
    Default: default

#####  Environment Variables #####
Mappings:
  StagesMap:
    sandbox:
      VariableName: Value
    staging:
      VariableName: Value
    production:
      VariableName: Value

#####  Template Conditions #####
Conditions:
  CreateSandboxResources: !Equals [!Ref Stage, sandbox]

Resources:
  #####  API Gateway #####
  PetStoreApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      MethodSettings:
        - HttpMethod: "*"
          LoggingLevel: INFO
          MetricsEnabled: true
          ResourcePath: /*
      StageName: Prod
      TracingEnabled: true
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: ./swagger.yaml

  #####  Lambda Functions #####
  GetPetFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetPetFunction
      Runtime: nodejs12.x
      Handler: cmd/lambdas/get-pet/app.lambdaHandler
      CodeUri: src/
      MemorySize: 512
      Tracing: Active
      Events:
        GetPetApi:
          Type: Api
          Properties:
            RestApiId: !Ref "PetStoreApiGateway"
            Path: /pet/{petId}
            Method: GET
      Policies:
        - AWSLambdaBasicExecutionRole



Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL to get a pet"
    Value: !Sub "https://${PetStoreApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/pet/{petId}"
