AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >

  nodejs-sam-bootstrap
  SAM Template for nodejs-sam-bootstrap

#####  Globals for Lambda functions #####
Globals:
  Function:
    Timeout: 5
    Environment:
      Variables:
        AccountId: !Ref AWS::AccountId
        Region: "eu-west-1"
        NEWRELIC_HANDLER: newrelic-lambda-wrapper.handler
        NEW_RELIC_LAMBDA_HANDLER: app.lambdaHandler

#####  Input Parameters #####
Parameters:
  Stage:
    Type: String
    Description: Parameter for getting the deployment stage
    Default: default
  NewrelicExtensionLayer:
    Type: String
    Description: NewRelic extension layer

#####  Environment Variables #####
Mappings:
  StagesMap:
    sandbox:
      NewRelicAccountId: 0
      NewRelicLicenseSecretKeyArn: arn:aws:secretsmanager:eu-west-1::secret:NEW_RELIC_NON_EXISTING_LICENSE_KEY
    staging:
      NewRelicAccountId: '{{resolve:ssm:/stg/newrelic-account-id}}'
      NewRelicLicenseSecretKeyArn: arn:aws:secretsmanager:eu-west-1::secret:NEW_RELIC_LICENSE_KEY-staging
    production:
      NewRelicAccountId: '{{resolve:ssm:/prd/newrelic-account-id}}'
      NewRelicLicenseSecretKeyArn: arn:aws:secretsmanager:eu-west-1::secret:NEW_RELIC_LICENSE_KEY-production

#####  Template Conditions #####
Conditions:
  CreateSandboxResources: !Equals [!Ref Stage, sandbox]

Resources:
  #####  Lambda Functions #####
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cmd/lambdas/hello-world/app.lambdaHandler
      CodeUri: src/
      Runtime: nodejs16.x
      Environment:
        Variables:
          NEW_RELIC_ACCOUNT_ID: !FindInMap
            - StagesMap
            - Ref: Stage
            - NewRelicAccountId
      Layers:
        - !Ref NewrelicExtensionLayer
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !FindInMap
              - StagesMap
              - Ref: Stage
              - NewRelicLicenseSecretKeyArn
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello-world
            Method: GET

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL to print Hello, World!"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello-world/"
